### PR TITLE
Update eslint dependency

### PR DESCRIPTION
**Pull request by castrinho8**
Update eslint dependency caused by a compatibility error with eslint-config-airbnb

### CODE REVIEW

**Comment by ssaavedra** [comment]
LGTM

**Comment by ssaavedra** [comment]
Parece que non funciona o plugin...

**Comment by ssaavedra** [comment]
:shipit:

**Comment by ssaavedra** [comment]
Xa foi; era un tema de race conditions.

**Comment by castrinho8** [comment]
LGTM

**Pull request merged**
